import { CustomNote, NoteTemplateId, ActionItem, Flashcard, MindMapNode } from '../types';

export async function generateCustomNote(
  recordingId: string,
  recordingTitle: string,
  transcript: string,
  templateId: NoteTemplateId,
  customPrompt?: string,
  apiKey?: string,
  apiEndpoint?: string,
  apiModel?: string
): Promise<CustomNote> {

  // Use the configured provider when a key is available; the local engine remains the fallback.
  if (apiKey && apiKey.trim().length > 0) {
    try {
      const llmResult = await fetchLlmNote(
        transcript,
        templateId,
        customPrompt,
        apiKey,
        apiEndpoint,
        apiModel
      );
      if (llmResult) {
        return {
          id: 'note-' + Date.now(),
          recordingId,
          title: `${recordingTitle} - ${getTemplateTitle(templateId)}`,
          date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
          templateId,
          summary: llmResult.summary,
          contentMarkdown: llmResult.contentMarkdown,
          actionItems: llmResult.actionItems,
          flashcards: llmResult.flashcards,
          mindMap: llmResult.mindMap,
          tags: llmResult.tags,
          customPrompt
        };
      }
    } catch (e) {
      console.warn('Configured API call failed, falling back to local NLP engine:', e);
    }
  }

  // Fallback / Built-in zero-config intelligent NLP note synthesizer
  return generateLocalNLPNote(recordingId, recordingTitle, transcript, templateId, customPrompt);
}

function getTemplateTitle(templateId: NoteTemplateId): string {
  switch (templateId) {
    case 'summarized': return 'Summarized';
    case 'flash-cards': return 'Flash Cards';
    case 'notes': return 'Notes';
    case 'possible-questions': return 'Possible Asked Questions';
    default: return 'Note';
  }
}

function cleanTranscriptSentences(transcript: string): string[] {
  return transcript
    .split(/(?<=[.!?])\s+|\n+/)
    .map(sentence => sentence.replace(/\s+/g, ' ').trim())
    .filter(sentence => sentence.length > 20)
    .filter(sentence => !/^(intro|summary|transcript|audio|notes)$/i.test(sentence))
    .slice(0, 8);
}

function buildKeyPoints(sentences: string[]): string[] {
  return sentences
    .map(sentence => sentence.replace(/^[-•*]\s*/, ''))
    .map(sentence => sentence.replace(/\b(?:overall|basically|really|very|just|simply)\b/gi, '').trim())
    .filter(sentence => sentence.length > 20)
    .slice(0, 5);
}

function normalizeParsedNotePayload(parsed: any): {
  summary: string;
  contentMarkdown: string;
  actionItems?: ActionItem[];
  flashcards?: Flashcard[];
  mindMap?: MindMapNode[];
  tags: string[];
} | null {
  if (!parsed || typeof parsed !== 'object') return null;

  const summary = typeof parsed.summary === 'string' && parsed.summary.trim().length > 0
    ? parsed.summary.trim()
    : 'AI generated note summary.';

  const contentMarkdown = typeof parsed.contentMarkdown === 'string' && parsed.contentMarkdown.trim().length > 0
    ? parsed.contentMarkdown.trim()
    : '## Note\n\nAI-generated content was returned without a structured body.';

  const tags = Array.isArray(parsed.tags) && parsed.tags.length > 0
    ? parsed.tags.filter((tag: unknown): tag is string => typeof tag === 'string' && tag.trim().length > 0).map((tag: string) => tag.trim())
    : ['AI Generated'];

  return {
    summary,
    contentMarkdown,
    actionItems: Array.isArray(parsed.actionItems) ? parsed.actionItems as ActionItem[] : undefined,
    flashcards: Array.isArray(parsed.flashcards) ? parsed.flashcards as Flashcard[] : undefined,
    mindMap: Array.isArray(parsed.mindMap) ? parsed.mindMap as MindMapNode[] : undefined,
    tags
  };
}

// Local Zero-Config Heuristic NLP Synthesizer
function generateLocalNLPNote(
  recordingId: string,
  recordingTitle: string,
  transcript: string,
  templateId: NoteTemplateId,
  customPrompt?: string
): CustomNote {
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const sentences = transcript.split(/(?<=[.?!])\s+/).filter(s => s.trim().length > 5);

  let summary = '';
  let contentMarkdown = '';
  let actionItems: ActionItem[] | undefined;
  let flashcards: Flashcard[] | undefined;
  let mindMap: MindMapNode[] | undefined;
  let tags: string[] = ['VoiceNote', 'AutoGenerated'];

  const keyFacts = buildKeyPoints(cleanTranscriptSentences(transcript));

  switch (templateId) {
    case 'summarized': {
      summary = keyFacts.length > 0 ? keyFacts.join(' ') : 'Key points from the transcript.';
      tags = ['Summary', 'Key Points'];
      contentMarkdown = `# Summary: ${recordingTitle}\n\n**Date:** ${dateStr}\n\n## Key points\n${keyFacts.map(fact => `- ${fact}`).join('\n') || '- No key points extracted.'}\n`;
      break;
    }

    case 'flash-cards': {
      summary = 'Quick questions and answers extracted from the transcript.';
      tags = ['Flashcards', 'Study'];

      flashcards = keyFacts.map((fact, idx) => ({
        id: `fc-${idx}`,
        question: `Question ${idx + 1}: What is the main point?`,
        answer: fact
      }));

      contentMarkdown = `# Flash Cards: ${recordingTitle}\n\n**Date:** ${dateStr}\n\n## Q&A\n${flashcards.map((fc, i) => `### ${i + 1}. ${fc.question}\n**Answer:** ${fc.answer}\n`).join('\n') || 'No flash cards generated.'}\n`;
      break;
    }

    case 'notes': {
      summary = 'Important details organized into short notes.';
      tags = ['Notes', 'Useful Information'];

      const noteBullets = keyFacts.length > 0 ? keyFacts : sentences.slice(0, 4);
      contentMarkdown = `# Notes: ${recordingTitle}\n\n**Date:** ${dateStr}\n\n## Important details\n${noteBullets.map(item => `- ${item}`).join('\n') || '- No notes available.'}\n`;
      break;
    }

    case 'possible-questions': {
      summary = 'Likely questions that can be answered from this transcript.';
      tags = ['Questions', 'Review'];

      const possibleQuestions = keyFacts.length > 0
        ? keyFacts.map((fact, idx) => ({
            id: `q-${idx}`,
            question: `What does this point mean in practical terms?`,
            answer: fact
          }))
        : [{ id: 'q-1', question: 'What is the main topic?', answer: 'The transcript content.' }];

      contentMarkdown = `# Possible Asked Questions: ${recordingTitle}\n\n**Date:** ${dateStr}\n\n## Likely questions\n${possibleQuestions.map((item, idx) => `### ${idx + 1}. ${item.question}\n**Answer:** ${item.answer}\n`).join('\n')}`;
      break;
    }
  }

  return {
    id: 'note-' + Date.now(),
    recordingId,
    title: `${recordingTitle} - ${getTemplateTitle(templateId)}`,
    date: dateStr,
    templateId,
    summary,
    contentMarkdown,
    actionItems,
    flashcards,
    mindMap,
    tags,
    customPrompt
  };
}

// Supports Gemini and providers exposing an OpenAI-compatible chat completions endpoint.
async function fetchLlmNote(
  transcript: string,
  templateId: NoteTemplateId,
  customPrompt: string | undefined,
  apiKey: string,
  apiEndpoint = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent',
  apiModel = 'gemini-1.5-flash'
): Promise<{ summary: string; contentMarkdown: string; actionItems?: ActionItem[]; flashcards?: Flashcard[]; mindMap?: MindMapNode[]; tags: string[] } | null> {
  const promptText = `You are an expert AI note assistant. Transform the following audio transcript into a structured note.

Transcript: "${transcript}"

Template Mode: ${templateId}
${customPrompt ? `Custom User Instructions: "${customPrompt}"` : ''}

Format your output as a JSON object with this exact schema:
{
  "summary": "Brief 1-2 sentence overview",
  "contentMarkdown": "Full rich markdown note with headings, bullet points, and formatting",
  "tags": ["tag1", "tag2"],
  "actionItems": [ { "id": "1", "task": "Task description", "completed": false, "priority": "high|medium|low" } ]
}
Return ONLY valid raw JSON without markdown code blocks.`;

  const isGeminiEndpoint = apiEndpoint.includes('generativelanguage.googleapis.com');
  const url = isGeminiEndpoint
    ? `${apiEndpoint.replace(/\/$/, '')}?key=${encodeURIComponent(apiKey)}`
    : apiEndpoint;
  const body = isGeminiEndpoint
    ? { contents: [{ parts: [{ text: promptText }] }] }
    : {
      model: apiModel,
      messages: [
        { role: 'system', content: 'You are an expert AI note assistant.' },
        { role: 'user', content: promptText }
      ],
      response_format: { type: 'json_object' }
    };
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(isGeminiEndpoint ? {} : { Authorization: `Bearer ${apiKey}` })
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw new Error(`Configured API error status: ${response.status}`);
  }

  const data = await response.json();
  const textOutput = isGeminiEndpoint
    ? data?.candidates?.[0]?.content?.parts?.[0]?.text
    : data?.choices?.[0]?.message?.content;
  if (!textOutput) return null;

  const cleanJsonText = String(textOutput).replace(/```json/gi, '').replace(/```/g, '').trim();

  try {
    const parsed = JSON.parse(cleanJsonText);
    const normalized = normalizeParsedNotePayload(parsed);
    if (normalized) return normalized;
  } catch (error) {
    console.warn('Configured API returned malformed JSON for note conversion. Falling back to a safe output format.', error);
  }

  const fallbackText = cleanJsonText || String(textOutput);
  return {
    summary: 'AI generated note summary.',
    contentMarkdown: fallbackText.length > 0 ? fallbackText : '## Note\n\nAI-generated content was returned without a structured body.',
    tags: ['AI Generated']
  };
}
