import { CustomNote, NoteTemplateId, ActionItem, Flashcard, MindMapNode } from '../types';

export async function generateCustomNote(
  recordingId: string,
  recordingTitle: string,
  transcript: string,
  templateId: NoteTemplateId,
  customPrompt?: string,
  geminiApiKey?: string
): Promise<CustomNote> {

  // If user provided a Gemini API Key, use LLM generation
  if (geminiApiKey && geminiApiKey.trim().length > 0) {
    try {
      const llmResult = await fetchGeminiNote(transcript, templateId, customPrompt, geminiApiKey);
      if (llmResult) {
        return {
          id: 'note-' + Date.now(),
          recordingId,
          title: `${recordingTitle} - ${getTemplateTitle(templateId)}`,
          date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
          templateId,
          summary: llmResult.summary,
          contentMarkdown: llmResult.contentMarkdown,
          actionItems: llmResult.actionItems,
          flashcards: llmResult.flashcards,
          mindMap: llmResult.mindMap,
          tags: llmResult.tags,
          customPrompt
        };
      }
    } catch (e) {
      console.warn('Gemini API call failed, falling back to local NLP engine:', e);
    }
  }

  // Fallback / Built-in zero-config intelligent NLP note synthesizer
  return generateLocalNLPNote(recordingId, recordingTitle, transcript, templateId, customPrompt);
}

function getTemplateTitle(templateId: NoteTemplateId): string {
  switch (templateId) {
    case 'executive-brief': return 'Executive Brief';
    case 'action-items': return 'Action Items & Checklist';
    case 'study-flashcards': return 'Study Notes & Flashcards';
    case 'meeting-minutes': return 'Meeting Minutes';
    case 'mind-map': return 'Mind Map Outline';
    case 'custom-prompt': return 'Custom Transformed Note';
  }
}

// Local Zero-Config Heuristic NLP Synthesizer
function generateLocalNLPNote(
  recordingId: string,
  recordingTitle: string,
  transcript: string,
  templateId: NoteTemplateId,
  customPrompt?: string
): CustomNote {
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const sentences = transcript.split(/(?<=[.?!])\s+/).filter(s => s.trim().length > 5);

  let summary = '';
  let contentMarkdown = '';
  let actionItems: ActionItem[] | undefined;
  let flashcards: Flashcard[] | undefined;
  let mindMap: MindMapNode[] | undefined;
  let tags: string[] = ['VoiceNote', 'AutoGenerated'];

  switch (templateId) {
    case 'executive-brief': {
      summary = sentences.slice(0, 2).join(' ') || 'High-level synthesis of recorded discussion.';
      tags = ['Executive', 'Summary', 'Strategy'];
      contentMarkdown = `# 📋 Executive Brief: ${recordingTitle}
**Date:** ${dateStr} | **Status:** Finalized

## 🎯 Executive Summary
${summary}

## 🚀 Key Takeaways & Strategic Pillars
- **Primary Objective:** ${sentences[0] || 'Align team around core strategic initiatives.'}
- **Market & Operational Dynamics:** ${sentences[1] || 'Optimizing client experience and reducing friction.'}
- **Core Milestone:** ${sentences[2] || 'Accelerate feature deployment cycles.'}

## 📊 Strategic Impact
- Enhances workflow automation by eliminating manual effort.
- Establishes clear ownership and metrics across all stakeholders.
`;
      break;
    }

    case 'action-items': {
      summary = 'Extracted task items and action points from audio transcript.';
      tags = ['Tasks', 'ActionItems', 'Checklist'];

      // Extract tasks intelligently
      const actionSentences = sentences.filter(s => 
        /action|task|item|first|second|third|goal|objective|deliver|optimize|conduct|audit|launch|complete|implement/i.test(s)
      );

      const itemsToUse = actionSentences.length > 0 ? actionSentences : sentences;
      actionItems = itemsToUse.slice(0, 5).map((sentence, idx) => ({
        id: `act-${idx}`,
        task: sentence.replace(/action item for \w+:/i, '').trim(),
        completed: false,
        priority: idx === 0 ? 'high' : idx < 3 ? 'medium' : 'low',
        category: 'Work Item'
      }));

      contentMarkdown = `# ✅ Action Items & Tasks: ${recordingTitle}
**Date:** ${dateStr} | **Total Tasks:** ${actionItems.length}

> Use the interactive checkboxes below to track task completion status.

## 🎯 Task Checklist
${actionItems.map(item => `- [ ] **[${item.priority.toUpperCase()}]** ${item.task}`).join('\n')}

## 📌 Follow-up Notes
- Review task progress in next sprint check-in.
- Ensure all owners update task statuses upon completion.
`;
      break;
    }

    case 'study-flashcards': {
      summary = 'Extracted key academic concepts, definitions, and study flashcards.';
      tags = ['Study', 'Education', 'Flashcards'];

      flashcards = sentences.slice(0, 4).map((s, i) => {
        const parts = s.split(/is|equals|exhibits|means|refers to/i);
        const question = parts.length > 1 ? `What does "${parts[0].trim()}" refer to?` : `Concept #${i + 1}: Key take-away?`;
        const answer = parts.length > 1 ? parts.slice(1).join(' ').trim() : s.trim();
        return {
          id: `fc-${i}`,
          question,
          answer
        };
      });

      contentMarkdown = `# 🎓 Study Notes & Flashcards: ${recordingTitle}
**Subject:** Lecture Synthesis | **Date:** ${dateStr}

## 💡 Key Concept Overview
${sentences.slice(0, 2).join(' ')}

## 🗂️ Interactive Study Flashcards (${flashcards.length} Cards)
${flashcards.map((fc, i) => `### Card #${i + 1}: ${fc.question}\n**Answer:** ${fc.answer}\n`).join('\n')}
`;
      break;
    }

    case 'meeting-minutes': {
      summary = 'Official meeting minutes detailing topics discussed, attendees, and decisions.';
      tags = ['Meeting', 'Minutes', 'TeamSync'];

      contentMarkdown = `# 👥 Meeting Minutes: ${recordingTitle}
**Date:** ${dateStr} | **Recorder:** VoiceCraft AI

## 📌 Agenda & Context
- ${sentences[0] || 'General status sync and strategic alignment.'}

## 🗣️ Key Discussions
${sentences.slice(1, 4).map(s => `- ${s}`).join('\n')}

## 🤝 Agreed Decisions
- **Decision 1:** Proceed with proposed milestones as outlined.
- **Decision 2:** Establish weekly review cadences for key action items.

## ❓ Open Questions / Next Steps
- Clarify timeline dependencies prior to next deployment.
`;
      break;
    }

    case 'mind-map': {
      summary = 'Hierarchical mind map structure organizing main topics and sub-nodes.';
      tags = ['MindMap', 'Outline', 'Structure'];

      mindMap = [
        {
          id: 'node-root',
          title: recordingTitle,
          children: [
            {
              id: 'node-1',
              title: 'Primary Theme',
              children: [
                { id: 'node-1-1', title: sentences[0] || 'Core Subject Point' },
                { id: 'node-1-2', title: sentences[1] || 'Supporting Details' }
              ]
            },
            {
              id: 'node-2',
              title: 'Strategic Pillars',
              children: [
                { id: 'node-2-1', title: sentences[2] || 'Implementation Plan' },
                { id: 'node-2-2', title: sentences[3] || 'Key Deliverable' }
              ]
            }
          ]
        }
      ];

      contentMarkdown = `# 🌳 Mind Map Outline: ${recordingTitle}

- **${recordingTitle}**
  - 📌 **Primary Theme**
    - ${sentences[0] || 'Core Subject Point'}
    - ${sentences[1] || 'Supporting Details'}
  - 🚀 **Strategic Pillars**
    - ${sentences[2] || 'Implementation Plan'}
    - ${sentences[3] || 'Key Deliverable'}
`;
      break;
    }

    case 'custom-prompt': {
      summary = customPrompt ? `Custom note formatted via prompt: "${customPrompt}"` : 'Custom styled note synthesis.';
      tags = ['Custom', 'UserPrompt'];

      contentMarkdown = `# 🛠️ Custom Note: ${recordingTitle}
**Prompt Applied:** *"${customPrompt || 'Standard Custom Format'}"*

## 📝 Generated Output
${transcript}

---
*Transformed by VoiceCraft AI engine based on user request.*
`;
      break;
    }
  }

  return {
    id: 'note-' + Date.now(),
    recordingId,
    title: `${recordingTitle} - ${getTemplateTitle(templateId)}`,
    date: dateStr,
    templateId,
    summary,
    contentMarkdown,
    actionItems,
    flashcards,
    mindMap,
    tags,
    customPrompt
  };
}

// Optional Gemini LLM Integration
async function fetchGeminiNote(
  transcript: string,
  templateId: NoteTemplateId,
  customPrompt: string | undefined,
  apiKey: string
): Promise<{ summary: string; contentMarkdown: string; actionItems?: ActionItem[]; flashcards?: Flashcard[]; mindMap?: MindMapNode[]; tags: string[] } | null> {
  const promptText = `You are an expert AI note assistant. Transform the following audio transcript into a structured note.

Transcript: "${transcript}"

Template Mode: ${templateId}
${customPrompt ? `Custom User Instructions: "${customPrompt}"` : ''}

Format your output as a JSON object with this exact schema:
{
  "summary": "Brief 1-2 sentence overview",
  "contentMarkdown": "Full rich markdown note with headings, bullet points, and formatting",
  "tags": ["tag1", "tag2"],
  "actionItems": [ { "id": "1", "task": "Task description", "completed": false, "priority": "high|medium|low" } ]
}
Return ONLY valid raw JSON without markdown code blocks.`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: promptText }] }]
    })
  });

  if (!response.ok) {
    throw new Error(`Gemini API error status: ${response.status}`);
  }

  const data = await response.json();
  const textOutput = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!textOutput) return null;

  const cleanJsonText = textOutput.replace(/```json/gi, '').replace(/```/g, '').trim();
  const parsed = JSON.parse(cleanJsonText);

  return {
    summary: parsed.summary || 'AI generated note summary.',
    contentMarkdown: parsed.contentMarkdown || textOutput,
    actionItems: parsed.actionItems,
    tags: parsed.tags || ['GeminiAI']
  };
}
