import { CustomNote, AudioRecording } from '../types';

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportNoteAsMarkdown(note: CustomNote) {
  const sanitizeTitle = note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  downloadFile(note.contentMarkdown, `${sanitizeTitle}.md`, 'text/markdown');
}

export function exportNoteAsText(note: CustomNote) {
  const sanitizeTitle = note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const plainText = note.contentMarkdown.replace(/#|\*|`|>|- \[ \]/g, '').trim();
  downloadFile(plainText, `${sanitizeTitle}.txt`, 'text/plain');
}

export function exportBundleAsJson(note: CustomNote, recording?: AudioRecording) {
  const sanitizeTitle = note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const bundleData = {
    note,
    recording: recording ? {
      title: recording.title,
      date: recording.date,
      duration: recording.duration,
      transcript: recording.transcript,
      segments: recording.segments
    } : null,
    exportedAt: new Date().toISOString(),
    generator: 'VoiceCraft AI Studio'
  };
  downloadFile(JSON.stringify(bundleData, null, 2), `${sanitizeTitle}_bundle.json`, 'application/json');
}

export function printFormattedNote(note: CustomNote) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${note.title}</title>
        <style>
          body { font-family: 'Plus Jakarta Sans', sans-serif; padding: 40px; color: #0f172a; line-height: 1.6; }
          h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
          blockquote { border-left: 4px solid #4f46e5; padding-left: 15px; color: #475569; font-style: italic; }
          .meta { font-size: 0.9em; color: #64748b; margin-bottom: 20px; }
          .footer { margin-top: 50px; font-size: 0.8em; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 15px; }
        </style>
      </head>
      <body>
        <div class="meta">Date: ${note.date} | Category: ${note.tags.join(', ')}</div>
        <div>${note.contentMarkdown.replace(/\n/g, '<br/>')}</div>
        <div class="footer">Generated by VoiceCraft AI Note Studio</div>
        <script>
          window.onload = function() { window.print(); window.close(); }
        </script>
      </body>
    </html>
  `;
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (e) {
    console.error('Copy to clipboard failed:', e);
    return false;
  }
}
