import { CustomNote, AudioRecording } from '../types';

function sanitizeFileName(title: string) {
  return title.replace(/[^a-z0-9]+/gi, '_').replace(/^_+|_+$/g, '').toLowerCase() || 'note';
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function markdownToHtml(markdown: string) {
  const escaped = escapeHtml(markdown);

  return escaped
    .replace(/\n\n+/g, '</p><p>')
    .replace(/\n/g, '<br />')
    .replace(/### (.*?)(<br \/>|$)/g, '<h3>$1</h3>')
    .replace(/## (.*?)(<br \/>|$)/g, '<h2>$1</h2>')
    .replace(/# (.*?)(<br \/>|$)/g, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code>$1</code>')
    .replace(/- \[(.*?)\]/g, '<input type="checkbox" disabled checked /> $1')
    .replace(/- \[(.*?)\]/g, '<input type="checkbox" disabled /> $1')
    .replace(/- (.*?)(<br \/>|$)/g, '<li>$1</li>')
    .replace(/<li>/g, '<ul><li>')
    .replace(/<\/li>/g, '</li>')
    .replace(/<\/li><li>/g, '</li><li>')
    .replace(/<\/li><\/ul><ul><li>/g, '</li><li>')
    .replace(/<\/ul><\/li>/g, '</li></ul>')
    .replace(/<p><h1>/g, '<h1>')
    .replace(/<\/h1><\/p>/g, '</h1>')
    .replace(/<p><h2>/g, '<h2>')
    .replace(/<\/h2><\/p>/g, '</h2>')
    .replace(/<p><h3>/g, '<h3>')
    .replace(/<\/h3><\/p>/g, '</h3>')
    .replace(/^(?!<h|<ul|<li|<p|<br|<input)(.*)$/g, '<p>$1</p>');
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportNoteAsMarkdown(note: CustomNote) {
  const safeTitle = sanitizeFileName(note.title);
  downloadFile(note.contentMarkdown, `${safeTitle}.md`, 'text/markdown');
}

export function exportNoteAsText(note: CustomNote) {
  const safeTitle = sanitizeFileName(note.title);
  const plainText = note.contentMarkdown.replace(/#|\*|`|>|- \[ \]/g, '').trim();
  downloadFile(plainText, `${safeTitle}.txt`, 'text/plain');
}

export function exportTextAsPdf(content: string, filename: string) {
  const printWindow = window.open('', '_blank', 'noopener,noreferrer');
  if (!printWindow) return;

  const bodyHtml = markdownToHtml(content);

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${escapeHtml(filename)}</title>
        <style>
          @page { size: A4; margin: 18mm; }
          body {
            font-family: 'Segoe UI', sans-serif;
            color: #111827;
            background: white;
            padding: 0;
            margin: 0;
            line-height: 1.6;
          }
          .doc {
            max-width: 100%;
            padding: 12mm;
          }
          h1, h2, h3 {
            color: #1f2937;
            margin-top: 1.2em;
            margin-bottom: 0.4em;
          }
          h1 { font-size: 2rem; }
          h2 { font-size: 1.5rem; }
          h3 { font-size: 1.1rem; }
          ul { padding-left: 1.2rem; }
          code { background: #f3f4f6; padding: 0.15rem 0.3rem; border-radius: 0.25rem; }
          .meta { font-size: 0.8rem; color: #4b5563; margin-bottom: 1.25rem; }
          .footer { margin-top: 2rem; font-size: 0.8rem; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 0.75rem; }
        </style>
      </head>
      <body>
        <div class="doc">
          <div class="meta">Generated by VoiceCraft AI Studio</div>
          <div>${bodyHtml}</div>
          <div class="footer">Exported as PDF</div>
        </div>
        <script>
          window.onload = function() {
            setTimeout(() => {
              window.print();
              window.close();
            }, 250);
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

export function exportNoteAsPdf(note: CustomNote) {
  const safeTitle = sanitizeFileName(note.title);
  exportTextAsPdf(note.contentMarkdown, `${safeTitle}.pdf`);
}

export function exportBundleAsJson(note: CustomNote, recording?: AudioRecording) {
  const sanitizeTitle = note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const bundleData = {
    note,
    recording: recording ? {
      title: recording.title,
      date: recording.date,
      duration: recording.duration,
      transcript: recording.transcript,
      segments: recording.segments
    } : null,
    exportedAt: new Date().toISOString(),
    generator: 'VoiceCraft AI Studio'
  };
  downloadFile(JSON.stringify(bundleData, null, 2), `${sanitizeTitle}_bundle.json`, 'application/json');
}

export function printFormattedNote(note: CustomNote) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${note.title}</title>
        <style>
          body { font-family: 'Plus Jakarta Sans', sans-serif; padding: 40px; color: #0f172a; line-height: 1.6; }
          h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
          blockquote { border-left: 4px solid #4f46e5; padding-left: 15px; color: #475569; font-style: italic; }
          .meta { font-size: 0.9em; color: #64748b; margin-bottom: 20px; }
          .footer { margin-top: 50px; font-size: 0.8em; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 15px; }
        </style>
      </head>
      <body>
        <div class="meta">Date: ${note.date} | Category: ${note.tags.join(', ')}</div>
        <div>${note.contentMarkdown.replace(/\n/g, '<br/>')}</div>
        <div class="footer">Generated by VoiceCraft AI Note Studio</div>
        <script>
          window.onload = function() { window.print(); window.close(); }
        </script>
      </body>
    </html>
  `;
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (e) {
    console.error('Copy to clipboard failed:', e);
    return false;
  }
}
